## Clock signal
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { clk_100Mhz }]; #IO_L12P_T1_MRCC_35 Sch=gclk[100]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { clk_100Mhz }];

set_property PACKAGE_PIN A11 [get_ports SDA]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]
set_property SLEW SLOW [get_ports SDA]
set_property PULLUP true [get_ports SDA]
set_property PACKAGE_PIN G13 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property PULLUP true [get_ports SCL]

set_property PACKAGE_PIN E1 [get_ports {reg_read[7]}]
set_property PACKAGE_PIN G4 [get_ports {reg_read[6]}]
set_property PACKAGE_PIN H4 [get_ports {reg_read[5]}]
set_property PACKAGE_PIN K2 [get_ports {reg_read[4]}]
set_property PACKAGE_PIN H5 [get_ports {reg_read[3]}]
set_property PACKAGE_PIN J5 [get_ports {reg_read[2]}]
set_property PACKAGE_PIN T9 [get_ports {reg_read[1]}]
set_property PACKAGE_PIN T10 [get_ports {reg_read[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reg_read[0]}]
set_property SLEW SLOW [get_ports SCL]
